---

- name: change password splunk
  shell: '/opt/splunkforwarder/bin/splunk edit user admin -password {{ attack_range_password }} -auth admin:Pl3ase-k1Ll-me:p'
  become: yes

- name: Change hostname
  shell: '/opt/splunkforwarder/bin/splunk set default-hostname {{ hostname }} -auth admin:{{ attack_range_password }}'
  become: yes

- name: Change servername
  shell: '/opt/splunkforwarder/bin/splunk set servername {{ hostname }} -auth admin:{{ attack_range_password }}'
  become: yes

- name: Restart Splunk
  shell: '/opt/splunkforwarder/bin/splunk restart'
  become: yes