---

- set_fact:
    technique: "{{ item }}"

- name: Run Atomic Red Team
  become: true
  shell: |
    pwsh -Command 'IEX (IWR https://raw.githubusercontent.com/redcanaryco/invoke-atomicredteam/master/install-atomicsfolder.ps1 -UseBasicParsing); 
    Install-AtomicsFolder -Force; 
    IEX (IWR https://raw.githubusercontent.com/redcanaryco/invoke-atomicredteam/master/install-atomicredteam.ps1); 
    Install-AtomicRedTeam -Force; Invoke-AtomicTest "{{ technique }}" -GetPrereqs; 
    Invoke-AtomicTest "{{ technique }}";
    Invoke-AtomicTest "{{ technique }}" -Cleanup'
  register: output_art

- debug:
    var: output_art.stdout_lines