- set_fact:
    technique: "{{ item }}"

- debug:
    var: technique

- name: Get requirements for Atomic Red Team Technique
  win_shell: |
    Import-Module "C:\AtomicRedTeam\invoke-atomicredteam\Invoke-AtomicRedTeam.psd1" -Force
    Invoke-AtomicTest "{{ technique }}" -GetPrereqs
  register: requirements
  ignore_errors: True

# - debug:
#     var: requirements

- name: Run specified Atomic Red Team Technique
  win_shell: |
    Import-Module "C:\AtomicRedTeam\invoke-atomicredteam\Invoke-AtomicRedTeam.psd1" -Force
    Invoke-AtomicTest "{{ technique }}" -Confirm:$false -TimeoutSeconds 300 -ExecutionLogPath C:\AtomicRedTeam\atc_execution.csv
  register: output_art

# - name: Save output atomic red team
#   set_fact:
#     output_art: "{{ output_art }}"
#     cacheable: yes

- debug:
    var: output_art.stdout_lines

- name: Cleanup after execution
  win_shell: |
    Import-Module "C:\AtomicRedTeam\invoke-atomicredteam\Invoke-AtomicRedTeam.psd1" -Force
    Invoke-AtomicTest "{{ technique }}" -Cleanup
  register: cleanup

# - debug:
#     var: cleanup
