- hosts: all
  gather_facts: False
  become: true
  roles:
    - role: linux_common
      when: use_prebuilt_images_with_packer == "0"
    - role: linux_universal_forwarder
      when: use_prebuilt_images_with_packer == "0"
    - role: linux_osquery
      when: use_prebuilt_images_with_packer == "0"
    - role: linux_sysmon
      when: use_prebuilt_images_with_packer == "0"