
- name: Git clone BadBlood
  win_shell: git clone https://github.com/P4T12ICK/BadBlood.git C:\Tools\BadBlood
  when: windows_domain_controller_run_badblood == "1"

- include_tasks: "run_badblood.yml"
  when: windows_domain_controller_run_badblood == "1"