---
# install nextron aurora agent https://www.nextron-systems.com/2021/11/13/aurora-sigma-based-edr-agent-preview/
- name: download the aurora-agent-lite-win-pack.zip file
  win_get_url:
    url: https://update1.nextron-systems.com/getupdate.php?product=aurora-agent-lite-win
    dest: '%TEMP%\aurora-agent.zip'

- name: unzip aurora-agent-lite-pack.zip
  win_unzip:
    src: '%TEMP%\aurora-agent.zip'
    dest: C:\aurora-agent-lite-win-pack

- name: download the aurora-agent license file
  win_get_url:
    url: https://portal.nextron-systems.com/api/lite/license/2022-2/6beda56036fbe184dd0950fd24acfd59_a1f1081c9d6f0dc29aa0e5609fadf855.lic
    dest: C:\aurora-agent-lite-win-pack\aurora-license.lic

- name: install aurora-agent as a service with standard config
  win_shell: .\aurora-agent.exe --install -c agent-config-standard.yml --json --logfile aurora_alerts.json.log
  args:
    chdir: C:\aurora-agent-lite-win-pack
  ignore_errors: yes
