--- 

- name: Download FireDrill
  win_get_url:
    url: "{{ firedrill_msi }}"
    dest: "{{ firedrill_dst_location }}"
    when: install

- name: Install FireDrill
  win_command: "{{ firedrill_dst_location }} /S"
  when: install
