---
- include: install_deb_uf.yml
- include: configure_outputs_conf.yml
- include: nginx_web_proxy.yml
- include: create_deploymentclient.yml
- include: configure_inputs.yml

- name: restart splunk
  become: true
  service:
    name: SplunkForwarder
    state: restarted

- name: restart nginx again
  become: true
  command: "nginx -s reload"
