---
# Install Phantom from RPM on a fresh AlmaLinux 8 instance

- name: Install decompressing tools for archive extraction
  yum:
    name: tar,gzip
    state: present

- name: Install patch commandlet 
  yum:
    name: patch
    state: present 

- name: Copy Splunk SOAR to server
  become: true
  copy:
    src: "../../apps/{{ phantom_app }}"
    dest: /tmp

- name: Copy SOAR patches to server
  become: true
  copy:
    src: "{{ item }}"
    dest: /tmp
  with_fileglob: "../../apps/*.patch"

- name: Create archive folders
  file:
    path: /tmp/extracted
    state: directory

- name: Exctract SOAR Archive
  unarchive:
    src: "/tmp/{{ phantom_app }}"
    dest: /tmp/extracted
    remote_src: yes

- name: Creates directory
  file:
    path: /opt/soar
    state: directory

- name: Patch OS-Checks of phantom \#1
  shell: patch /tmp/extracted/splunk-soar/install/operations/checks/os_check.py < /tmp/os_check.patch

- name: Patch OS-Checks of phantom \#2
  shell: patch /tmp/extracted/splunk-soar/install/install_common.py < /tmp/install_common.patch

- name: Patch OS-Checks of phantom \#3
  shell: patch /tmp/extracted/splunk-soar/install/operations/checks/correct_installer.py < /tmp/correct_installer.patch

- name: prepare phantom install script without apps
  become_user: almalinux
  shell: sudo /tmp/extracted/splunk-soar/soar-prepare-system --splunk-soar-home /opt/soar --no-prompt

- name: copy splunk soar folder
  shell: cp -r /tmp/extracted/splunk-soar /home/phantom/splunk-soar

- name: chown splunk soar folder
  shell: chown -R phantom. /home/phantom/splunk-soar

- name: run the phantom install script
  become_user: phantom
  shell: ./soar-install --splunk-soar-home /opt/soar --no-prompt --ignore-warnings
  args:
    chdir: /home/phantom/splunk-soar

# - name: upgrade all packages
#   yum:
#     name: '*'
#     state: latest

# - name: check if phantom is installed
#   stat: path=/opt/phantom
#   register: phantom_path

# - name: debug print if phantom is installed
#   debug: msg='phantom is already installed under /opt/phantom'
#   when: phantom_path.stat.exists


# - name: install the phantom setup rpm from the community repository
#   yum:
#     name: '{{ phantom_repo_url }}'
#     state: present

# # installing apps takes 15+ minutes longer, so later we will install just the apps we need
# - name: run the phantom install script without apps
#   shell: printf "{{phantom_community_username}}\n{{phantom_community_password}}\n" | /opt/phantom/bin/phantom_setup.sh install --no-prompt --without-apps --version={{phantom_version}}
#   async: 1800
#   poll: 60

# - name: install whois app
#   yum:
#     name: https://repo.phantom.us/phantom/4.10/apps/x86_64/phantom_whois-2.1.0.x86_64.rpm
#     state: present

# - name: install maxmind app
#   yum:
#     name: https://repo.phantom.us/phantom/4.10/apps/x86_64/phantom_maxmind-2.0.23.x86_64.rpm
#     state: present

# - name: install dns app
#   yum:
#     name: https://repo.phantom.us/phantom/4.10/apps/x86_64/phantom_dns-2.0.22.x86_64.rpm
#     state: present

# - name: install phishtank app
#   yum:
#     name: https://repo.phantom.us/phantom/4.10/apps/x86_64/phantom_phishtank-2.0.1.x86_64.rpm
#     state: present

# - name: install splunk app
#   yum:
#     name: https://repo.phantom.us/phantom/4.10/apps/x86_64/phantom_splunk-2.2.3.x86_64.rpm
#     state: present

# - name: install winrm app
#   yum:
#     name: https://repo.phantom.us/phantom/4.10/apps/x86_64/phantom_winrm-2.0.1.x86_64.rpm
#     state: present
