---
# This playbook contains common tasks in this role
#- include: add_vault_mirrors.yml

- include: resize_disk.yml

- include: install_phantom.yml
  when: cloud_provider != "local"

- include: install_phantom_local.yml
  when: cloud_provider == "local"
