## Variables for Splunk Search Head
splunk_binary_url: http://www.splunkresearch.com/splunk-7.2.6-c0bf0f679ce9-Linux-x86_64.tgz
splunk_binary: splunk-7.2.6-c0bf0f679ce9-Linux-x86_64.tgz
splunk_pass: changeme

# Apps
sysmon: True
stream: True
enterprise_security: True

# Apps binaries
splunk_stream_app: http://www.splunkresearch.com/splunk-stream_713.tgz
splunk_escu_app: http://www.splunkresearch.com/splunk-es-content-update_1037.tgz
splunk_es_app: http://www.splunkresearch.com/splunk-enterprise-security_530.spl

## Variables for Splunk Universal Forwarders
splunk_uf_indexer_ip: 10.0.0.10
splunk_uf_msi: http://www.splunkresearch.com/splunkforwarder-7.2.5-088f49762779-x64-release.msi

# Universal Forwarder deploy binaries
splunk_sysmon_ta: http://www.splunkresearch.com/add-on-for-microsoft-sysmon_800.tgz
splunk_stream_zip: http://www.splunkresearch.com/Splunk_TA_stream.zip
splunk_windows_ta: http://www.splunkresearch.com/splunk-add-on-for-microsoft-windows_600.tgz

#Variables for Firedrill 

#Variables for Firedrill 
install: False
firedrill_msi: http://www.splunkresearch.com/FiredrillAgent-installer-2.2.363.exe
firedrill_dst_location: C:\fd.exe

#Variables for Sysmon
win_temp_dir: 'c:\Program Files\ansible'
win_log_dir: 'c:\ProgramData\ansible\log'

win_sysmon: true
## as sysmon link is updated and hash change, chocolatey install can fails
## ansible win_get_url currently does not support checksum option
win_sysmon_direct: true
win_sysmon_url: 'https://download.sysinternals.com/files/Sysmon.zip'
win_sysmon_sha256: '848c3323324e8fa849024f87a2764f8575513463f339690056664861f99e4c5f'
## note: file should be in current or template directory with .j2 extension
#win_sysmon_template: SysmonConfig-Neo23x0-workstations.xml
#win_sysmon_template: SysmonConfig-moti.xml
#win_sysmon_template: SysmonConfig-TSwift.xml
win_sysmon_template: SysmonConfig-Verbose.xml

win_eventlog_maxsize: 315801600
win_eventlog_retention: 0
win_sysmon_eventlog_channels:
  - Microsoft-Windows-Sysmon/Operational

# Domain Controller
windows_domain_controller_info:
  dns_domain_name: vagrant.local
  domain_admin_password: vagrant
  domain_admin_user: administrator@vagrant.local
  safe_mode_password: Vagrant@123!
  state: domain_controller
