---
- name: copy nginx.conf to add kv logging to nginx plus
  file:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: copy default.conf to add the proxy information 
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf

- name: reload nginx
  systemd:
    daemon_reload: yes
    name: nginx
