- name: Check if stream app exists
  stat:
    path: /opt/splunk/etc/apps/Splunk_TA_stream
  register: stream_app

- name: download Stream app from S3 bucket
  get_url:
    url: 'https://attack-range-appbinaries.s3-us-west-2.amazonaws.com/{{ splunk_stream_app }}'
    dest: /tmp/stream_app.tgz
  when: stream_app.stat.exists == False

- name: Install stream app via REST
  uri:
    url: "https://127.0.0.1:8089/services/apps/local"
    method: POST
    user: "admin"
    password: "{{ splunk_pass }}"
    validate_certs: false
    body: "name=/tmp/stream_app.tgz&update=true&filename=true"
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    status_code: [ 200, 201 ]
    timeout: 30
  when: stream_app.stat.exists == False
  notify: restart splunk
