- name: Check we have downloaded splunk escu app
  stat:
    path: /tmp/escu_app.tgz
  register: escu_app

- name: Download escu app
  get_url:
    url: "{{ splunk_escu_app }}" 
    dest: /tmp/escu_app.tgz
    owner: splunk
    group: splunk
  notify: restart splunk
  when: escu_app.stat.exists == False

- name: install escu app
  unarchive:
    src: /tmp/escu_app.tgz
    dest: /opt/splunk/etc/apps
    remote_src: yes
  notify: restart splunk
  become: yes
  become_user: splunk
  when: escu_app.stat.exists == False
