- name: Check we have downloaded splunk windows ta
  stat:
    path: /tmp/windows_ta.tgz
  register: windows_ta

- name: Download windows ta
  get_url:
    url: "{{ splunk_windows_ta }}" 
    dest: /tmp/windows_ta.tgz
    owner: splunk
    group: splunk
  notify: restart splunk
  when: windows_ta.stat.exists == False

- name: install windows ta
  unarchive:
    src: /tmp/windows_ta.tgz
    dest: /opt/splunk/etc/apps
    remote_src: yes
  notify: restart splunk
  become: yes
  become_user: splunk
  when: windows_ta.stat.exists == False
