- name: Check we have downloaded splunk sysmon ta
  stat:
    path: /tmp/sysmon_ta.tgz
  register: sysmon_ta

- name: Download sysmon ta
  get_url:
    url: "{{ splunk_sysmon_ta }}" 
    dest: /tmp/sysmon_ta.tgz
    owner: splunk
    group: splunk
  notify: restart splunk
  when: sysmon_ta.stat.exists == False

- name: install sysmon ta
  unarchive:
    src: /tmp/sysmon_ta.tgz
    dest: /opt/splunk/etc/apps
    remote_src: yes
  notify: restart splunk
  become: yes
  become_user: splunk
  when: sysmon_ta.stat.exists == False
