- name: Check if sysmon ta exists
  stat:
    path: /opt/splunk/etc/apps/TA-microsoft-sysmon
  register: sysmon_ta

- name: copy sysmon ta
  copy:
    src: "{{ splunk_sysmon_ta_path }}"
    dest: /tmp/sysmon_ta.tgz
    mode: 0644
    local_follow: yes
  when: sysmon_ta.stat.exists == False

- name: Install sysmon ta app via REST
  uri:
    url: "https://127.0.0.1:8089/services/apps/local"
    method: POST
    user: "admin"
    password: "{{ splunk_pass }}"
    validate_certs: false
    body: "name=/tmp/sysmon_ta.tgz&update=true&filename=true"
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    status_code: [ 200, 201 ]
    timeout: 30
  when: sysmon_ta.stat.exists == False
  notify: restart splunk
