- hosts: all
  gather_facts: True
  vars:
    ansible_connection: winrm
    ansible_port: 5986
    ansible_winrm_server_cert_validation: ignore
    #ansible_winrm_transport: kerberos
    #ansible_winrm_kerberos_delegation: true
    hostname: win-dc
  roles:
    - windows_common
    - windows_dns_server
    - windows_domain_controller
    - windows_universal_forwarder
    - windows_aurora_agent
    - windows_caldera_agent
    - sysmon
    - red_team_tools
    - badblood
