- hosts: all
  gather_facts: True
#  tasks:
#    - debug:
#        msg: "{{ hostvars[inventory_hostname] }}"
  roles:
    - common
    - universal_forwarder
    - sysmon
    - firedrill
    - atomic_red_team
  vars_files:
    - ../vars/vars.yml 
