- hosts: win_dc
  gather_facts: True
  roles:
    - windows_common
    - windows_dns_server
    - windows_domain_controller
    - windows_universal_forwarder
    - sysmon
  vars_files:
    - ../vars/vars.yml
