- hosts: all
  gather_facts: True
#  tasks:
#    - debug:
#        msg: "{{ hostvars[inventory_hostname] }}"
  roles:
    - windows_common
    - universal_forwarder
    - sysmon
  vars_files:
    - ../vars/vars.yml
