---
#- include: set-hostname.yml
- include: windows-disable-defender.yml
- include: windows-enable-ps-logging.yml
- include: windows-enable-4688-cmd-line-audit.yml
- include: install_app_chocolatey.yml
  with_items:
    - "firefox"
    - "git"
    - "notepadplusplus"
    - "7zip"
    - "adobereader"
    - "python"


