- name: Check we have downloaded stream 
  win_stat:
    path: C:\splunk-stream.zip
  register: stream_zip

- name: Download Splunk Stream
  win_copy:
    src: "{{ splunk_stream_ta_path }}"
    dest: C:\splunk-stream.zip
  when: stream_zip.stat.exists == False

- name: Check we have unzip streams TA
  win_stat:
    path: "C:\\Program Files\\SplunkUniversalForwarder\\etc\\apps\\Splunk_TA_stream"
  register: stream_ta

- name: Unzip Stream App
  win_unzip: 
    src: C:\splunk-stream.zip
    dest: "C:\\Program Files\\SplunkUniversalForwarder\\etc\\apps\\"
    when: stream_ta.stat.exists == False || stream_ta.stat.exists == False

- name: Copy Stream Config File
  win_template:
    src: inputs.conf.j2
    dest: "C:\\Program Files\\SplunkUniversalForwarder\\etc\\apps\\Splunk_TA_stream\\local\\inputs.conf"
