- name: Download Splunk UF
  win_copy:
    src: "{{ splunk_uf_win_binary_path }}"
    dest: C:\splunkuf.msi

- name: Install Splunk_UF MSI
  win_package:
    path: C:\splunkuf.msi
    arguments: 'WINEVENTLOG_SEC_ENABLE=1 WINEVENTLOG_SYS_ENABLE=1 WINEVENTLOG_APP_ENABLE=1 SPLUNKPASSWORD=changeme RECEIVING_INDEXER="{{ splunk_uf_indexer_ip }}:9997" AGREETOLICENSE=YES /quiet'

- name: Start Splunk 
  win_service:
    name: SplunkForwarder
    state: started


