---

- name: Change dns server to domain controller
  win_dns_client:
    adapter_names: Ethernet
    ipv4_addresses: 10.0.1.5

- name: reboot | Rebooting Server
  win_reboot:

- name: Copy join domain script to host
  win_copy:
    src: "join_domain.ps1"
    dest: 'C:\join_domain.ps1'

- name: Run join domain
  win_shell: "C:\\join_domain.ps1 {{ windows_domain_controller_info['dns_domain_name'] }} {{ windows_domain_controller_info['domain_admin_user'] }} {{ windows_domain_controller_info['domain_admin_password'] }}"

#
# - win_domain_membership:
#     dns_domain_name: "{{ windows_domain_controller_info['dns_domain_name'] }}"
#     domain_admin_user: "{{ windows_domain_controller_info['domain_admin_user'] }}"
#     domain_admin_password: "{{ windows_domain_controller_info['domain_admin_password'] }}"
#     domain_ou_path: "OU=Windows,DC=splunkresearch,DC=local"
#     state: "domain"
#   register: domain_state

- win_reboot:
