---

- name: Change dns server to domain controller
  win_dns_client:
    adapter_names: Ethernet
    ipv4_addresses: 10.0.1.5

- name: reboot | Rebooting Server
  win_reboot:

- name: Copy join domain script to host
  win_copy:
    src: "join_domain.ps1"
    dest: 'C:\join_domain.ps1'

- name: Run join domain
  win_shell: "C:\\join_domain.ps1 attackrange.local Administrator@attackrange.local {{ win_password }}"

- win_reboot:
