---

- debug:
    var: ansible_distribution

- name: Disable Windows Defender for Windows 10
  ignore_errors: yes
  win_regedit:
    key: "HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Real-Time Protection"
    value: DisableRealTimeMonitoring
    datatype: dword
    data: 1
  when: ansible_distribution == "Microsoft Windows 10 Enterprise Evaluation"

- name: Disable Windows Defender in Windows Server windows_domain_controller
  win_shell: 'Uninstall-WindowsFeature -Name Windows-Defender'
  when: ansible_distribution == "Microsoft Windows Server 2016 Datacenter" or
        ansible_distribution == "Microsoft Windows Server 2016 Standard Evaluation"
