---

- name: Disable Windows Defender
  ignore_errors: yes
  win_regedit:
    key: "HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Real-Time Protection"
    value: DisableRealTimeMonitoring
    datatype: dword
    data: 1

- name: restart machine
  win_reboot:
