---
# This playbook contains common tasks in this role

- include: phantom.yml
- name: Finished
  debug: msg="Access your Phantom instance at http://10.0.0.11:443 with username 'admin' and password '{{ phantom_pass }}'"
